# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IoUCalculator
                                 A QGIS plugin
 : Tool to calculate IoU, Precision, Recall, and F1
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-25
        copyright            : (C) 2025 by Reut Keller Azulay
        email                : reutkeller@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IoUCalculator class from file IoUCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .iou_calculator import IoUCalculator
    return IoUCalculator(iface)
